; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
                        
; Uncomment one of following lines, if you haven't checked "Add IDP include path to ISPPBuiltins.iss" option
;#pragma include __INCLUDE__ + ";" + ReadReg(HKLM, "Software\Mitrich Software\Inno Download Plugin", "InstallDir")
;#pragma include __INCLUDE__ + ";" + "c:\lib\InnoDownloadPlugin"


[Languages]
;Name: en; MessagesFile: "compiler:Default.isl"
;Name: "he"; MessagesFile: "compiler:Languages\Hebrew.isl"
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"


#include <idp.iss>
; Language file must be included AFTER idp.iss
#include <idplang\default.iss>
          
; Language file must be included AFTER idp.iss
;#include <idplang\english.iss>

#define MyAppName "Israeli-IronChrome"
#define MyAppVersion "1.2"
#define MyAppPublisher "Defensia, Ltd."
#define MyAppURL "https://www.ironchrome.co.il/"
#define MyAppExeName32 "IsraeliIronChrome.bat"
#define MyAppExeName64 "IsraeliIronChrome64.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AllowNoIcons=no
;AppCopyright=lostprophet
AppId={{EA024684-437E-41A2-A17D-E600EDF56021}
AppName={#MyAppName}
;AppendDefaultDirName=false
;AppendDefaultGroupName=false
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
Compression=lzma2/max
  ;zip
  ;zip/1 through zip/9
  ;bzip
  ;bzip/1 through bzip/9
  ;lzma
  ;lzma/fast
  ;lzma/normal
  ;lzma/max
  ;lzma/ultra   (review memory requirements below before using)
  ;lzma/ultra64   (review memory requirements below before using)
  ;lzma2
  ;lzma2/fast
  ;lzma2/normal
  ;lzma2/max
  ;lzma2/ultra   (review memory requirements below before using)
  ;lzma2/ultra64   (review memory requirements below before using)
  ;none
;InternalCompressLevel=Ultra64
;DefaultDirName={reg:HKLM\Software\Wow6432Node\Ubisoft\Far Cry 3,InstallDir|{pf}\Far Cry 3}
DefaultDirName={localappdata}\Israeli-IronChrome
DefaultGroupName={#MyAppName}
;DiskSpanning=Yes
;DiskSliceSize=XXX
DisableProgramGroupPage=yes
InfoBeforeFile=מלל.txt
;LanguageDetectionMethod=none
;LicenseFile=F:\Copy\Copy\MAGYARITASOK\PROGRESS\Far Cry 3\installer\information.rtf
OutputBaseFilename=Israeli_IronChrome_v1.2
;OutputDir=C:\Users\lostprophet\Desktop
;OutputBaseFilename=farcry3hun_1.0
;PrivilegesRequired=admin
;PrivilegesRequired=none
PrivilegesRequired=lowest
;RestartIfNeededByRun=false
;SetupIconFile=F:\Copy\Copy\MAGYARITASOK\PROGRESS\Far Cry 3\installer\fc3_ikon.ico
ShowLanguageDialog=auto
SignTool=signtool
SolidCompression=yes
;SlicesPerDisk=XXX
;UninstallDisplayName=Far Cry 3 magyarítás
;UninstallFilesDir=interface
;UsePreviousGroup=false
;WizardImageFile="F:\Copy\Copy\MAGYARITASOK\PROGRESS\Far Cry 3\installer\installer.bmp"
;WizardSmallImageFile="F:\Copy\Copy\MAGYARITASOK\PROGRESS\Far Cry 3\installer\fc3_ikon.bmp"
VersionInfoVersion=1.2
VersionInfoCompany=Defensia
VersionInfoCopyright=Defensia
VersionInfoProductName=Israeli-IronChrome

;[Tasks]
;Name: "desktopicon32"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
;Name: "desktopicon64"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked


[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: 7za.exe; DestDir: {tmp}; Flags: dontcopy


[Icons]
Name: "{group}\{cm:UninstallProgram, {#MyAppName}}"; Filename: "{uninstallexe}"

Name: "{group}\Israeli-IronChrome 32 Bit";         Filename: "{app}\Israeli-IronChrome-x32-v42.0.2250.1-Flash\{#MyAppExeName32}"; WorkingDir: "{app}\Israeli-IronChrome-x32-v42.0.2250.1-Flash"; IconFilename: "{app}\Israeli-IronChrome-x32-v42.0.2250.1-Flash\IronChrome32.exe"; Comment: "{#MyAppExeName32}"; 
Name: "{userdesktop}\Israeli-IronChrome 32 Bit"; Filename: "{app}\Israeli-IronChrome-x32-v42.0.2250.1-Flash\{#MyAppExeName32}"; WorkingDir: "{app}\Israeli-IronChrome-x32-v42.0.2250.1-Flash"; IconFilename: "{app}\Israeli-IronChrome-x32-v42.0.2250.1-Flash\IronChrome32.exe"; Comment: "{#MyAppExeName32}";

Name: "{group}\Israeli-IronChrome 64 Bit - Maximum Security";         Filename: "{localappdata}\Chromium\{#MyAppExeName64}"; WorkingDir: "{localappdata}\Chromium"; IconFilename: "{localappdata}\Chromium\IronChrome64.exe"; Comment: "{#MyAppExeName32}";
Name: "{userdesktop}\Israeli-IronChrome 64 Bit - Maximum Security"; Filename: "{localappdata}\Chromium\{#MyAppExeName64}"; WorkingDir: "{localappdata}\Chromium"; IconFilename: "{localappdata}\Chromium\IronChrome64.exe"; Comment: "{#MyAppExeName64}";

;Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\Israeli-IronChrome-x32-v42.0.2250.1-Flash\{#MyAppExeName32}"; Tasks: desktopicon32
;Name: "{commondesktop}\{#MyAppName}"; Filename: "{localappdata}\Chromium\{#MyAppExeName64}"; Tasks: desktopicon64


;[Run]
;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, "&", "&&")}}"; Flags: nowait postinstall skipifsilent

           
; Let's change some of standard strings:
[CustomMessages]
;en.IDP_FormCaption = Downloading Israeli-IronCrome...
hebrew.IDP_FormCaption = "מוריד את Israeli-IronChrome"


[Dirs]
Name: "{app}"; Flags: uninsalwaysuninstall


[UninstallDelete]
;Type: filesandordirs; Name: "{localappdata}\Chromium\"
Type: filesandordirs; Name: "{app}"


[Code]
var  
  unzipTool   : String;   // path + filename of unzip helper for exec
  returnCode  : Integer;

procedure DoUnzip(source: String; targetdir: String);
begin
    // source contains tmp constant, so resolve it to path name
    source := ExpandConstant(source);

    unzipTool := ExpandConstant('{tmp}\7za.exe');

    if not FileExists(unzipTool)
    then MsgBox('UnzipTool not found: ' + unzipTool, mbError, MB_OK)
    else if not FileExists(source)
    then MsgBox('File was not found while trying to unzip: ' + source, mbError, MB_OK)
    else begin
         if Exec(unzipTool, ' x "' + source + '" -aoa -o"' + targetdir + '" -y',
                 '', SW_HIDE, ewWaitUntilTerminated, ReturnCode) = false
         then begin
             MsgBox('Unzip failed:' + source, mbError, MB_OK)
         end;
    end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
    if CurPageID = wpInstalling then //IDPForm.Page.ID then
    // wpWelcome, wpLicense, wpPassword, wpInfoBefore, wpUserInfo, wpSelectDir, wpSelectComponents,
    // wpSelectProgramGroup, wpSelectTasks, wpReady, wpPreparing, wpInstalling, wpInfoAfter, wpFinished
    begin                  

        //ForceDirectories(ExpandConstant('{localappdata}'));
        //ForceDirectories(ExpandConstant('{localappdata}\Israeli-IronChrome-x32-v42.0.2250.1-Flash'));
        //ForceDirectories(ExpandConstant('{localappdata}\Chromium'));
        //ForceDirectories(ExpandConstant('{localappdata}\TorExpertBundle'));

        DoUnzip(ExpandConstant('{tmp}\Israeli_IronChrome_v') + ExpandConstant('{#MyAppVersion}') + '.zip', ExpandConstant('{app}\'));
        DoUnzip(ExpandConstant('{tmp}\Israeli_IronChromeX64_v') + ExpandConstant('{#MyAppVersion}') + '.zip', ExpandConstant('{localappdata}\'));
        DoUnzip(ExpandConstant('{tmp}\TorExpertBundle.zip'), ExpandConstant('{localappdata}\'));
        
                                                     
        //Exec(ExpandConstant('{sys}\cmd.exe'),
        //                    '/c "' + ExpandConstant('{localappdata}\TorExpertBundle\add_tor_protocol_handler.bat') + '"',
        //                    '', SW_HIDE, ewWaitUntilTerminated, ReturnCode)

    end;
end;
            
procedure DoPreInstall();
begin
    //Exec(ExpandConstant('{sys}\cmd.exe'),
    //     '/c "' + ExpandConstant('{localappdata}\Israeli-IronChrome-x32-v42.0.2250.1-Flash\uninstall.bat') + '"',
    //     '', SW_HIDE, ewWaitUntilTerminated, ReturnCode)  
end;
                   
procedure DoPostInstall();
begin
  //Configure()
  RegWriteStringValue(HKEY_CURRENT_USER, 'Software\Defensia', 'InstallPath', ExpandConstant('{app}'));
  RegWriteStringValue(HKEY_CURRENT_USER, 'Software\Defensia', 'CurrentVersion', ExpandConstant('{#MyAppVersion}'));

  RegWriteStringValue(HKEY_CURRENT_USER, 'Software\Classes\Tor', '', 'TOR URI');
  RegWriteStringValue(HKEY_CURRENT_USER, 'Software\Classes\Tor', 'URL Protocol', '');
  RegWriteStringValue(HKEY_CURRENT_USER, 'Software\Classes\Tor', 'Content Type', 'application/TOR');
  RegWriteDWordValue( HKEY_CURRENT_USER, 'Software\Classes\Tor', 'EditFlags', 2);
  RegWriteStringValue(HKEY_CURRENT_USER, 'Software\Classes\Tor', 'FriendlyTypeName', 'Allows Executing TOR from inside web browsers such as Chrome');
  RegWriteStringValue(HKEY_CURRENT_USER, 'Software\Classes\Tor\DefaultIcon', '', '');
  RegWriteStringValue(HKEY_CURRENT_USER, 'Software\Classes\Tor\shell', '', 'open');
  RegWriteStringValue(HKEY_CURRENT_USER, 'Software\Classes\Tor\shell\open\command', '', ExpandConstant('{localappdata}') + '\TorExpertBundle\Tor\tor.exe');
end;
                   
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then DoPreInstall();
  if CurStep = ssPostInstall then DoPostInstall();
end;
              
procedure InitializeWizard(); 
begin          
    ExtractTemporaryFile('7za.exe');

    // allow user to continue installation if download fails.
    idpSetOption('AllowContinue',  '1');

    // Change from a simple overall progress bar to the detailed download view
    idpSetOption('DetailsVisible', '1');
    idpSetOption('DetailsButton',  '1');
    idpSetOption('RetryButton',    '1');
    idpSetOption('UserAgent',      'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2401.0 Safari/537.36');
    //idpSetOption('InvalidCert',    'ignore');
    idpSetOption('InvalidCert',    'stop');

    // Start the download after the "Ready to install" screen is shown
    idpDownloadAfter(wpReady);

    // reset files, previously added with idpAddFile() procedure
    idpClearFiles();

    // can also use {src}, WizardDirValue 
    idpAddFile('https://www.ironchrome.co.il/Israeli_IronChrome_v1.2.zip', ExpandConstant('{tmp}\Israeli_IronChrome_v') + ExpandConstant('{#MyAppVersion}') + '.zip'); 
    idpAddFile('https://www.ironchrome.co.il/Israeli_IronChromeX64_v1.2.zip', ExpandConstant('{tmp}\Israeli_IronChromeX64_v') + ExpandConstant('{#MyAppVersion}') + '.zip');
    idpAddFile('https://www.ironchrome.co.il/TorExpertBundle.zip', ExpandConstant('{tmp}\TorExpertBundle.zip')); 
    

end;


